version: '3.2'
services:

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      ENVIRONMENT: DOCKER
    links:
      - db

  redis:
    image: "redis:alpine"
    logging:
      driver: "none"

  db:
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: "none"
