# Generated by Django 3.2.7 on 2021-10-26 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trai', '0003_auto_20211025_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('action', models.IntegerField()),
                ('comment', models.CharField(max_length=20)),
            ],
        ),
    ]
