# Generated by Django 3.2.7 on 2021-10-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trai', '0004_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stochasticvalues',
            name='enter_d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stochasticvalues',
            name='enter_k',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stochasticvalues',
            name='exit_d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stochasticvalues',
            name='exit_k',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
