# Generated by Django 3.2.7 on 2021-10-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ohlc',
            old_name='datetime',
            new_name='timestamp',
        ),
    ]
