# Generated by Django 3.2.7 on 2021-10-25 09:39

from django.db import migrations, models
import trai.models


class Migration(migrations.Migration):

    dependencies = [
        ('trai', '0002_rename_datetime_ohlc_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='StochasticValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(default=trai.models.get_shifted_time)),
                ('enter_k', models.FloatField()),
                ('enter_d', models.FloatField()),
                ('exit_k', models.FloatField()),
                ('exit_d', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='ohlc',
            name='timestamp',
            field=models.DateTimeField(default=trai.models.get_shifted_time),
        ),
    ]
